name = "mail-system-api"
main = "src/index.js"
compatibility_date = "2024-08-01"
compatibility_flags = ["nodejs_compat"]

# KV Namespace for storing mail data
[[kv_namespaces]]
binding = "MAIL_STORAGE"
preview_id = "070b803c8c964a14a73c181d3e8d33b0"
id = "16a6bf29a0604f2383d3e6197f7ed61a"

# Environment variables (optional)
[vars]
ENVIRONMENT = "production"

# Custom domains (optional - configure after deployment)
# routes = [
#   { pattern = "api.yourdomain.com/*", custom_domain = true }
# ]

# Build configuration
[build]
command = ""

# Development configuration
[env.development.vars]
ENVIRONMENT = "development"