name = "mail-system-api"
main = "src/index.js"
compatibility_date = "2024-08-01"
compatibility_flags = ["nodejs_compat"]

# KV Namespace for storing mail data
[[kv_namespaces]]
binding = "MAIL_STORAGE"
preview_id = "your-preview-kv-namespace-id"
id = "your-production-kv-namespace-id"

# Environment variables (optional)
[vars]
ENVIRONMENT = "production"

# Custom domains (optional - configure after deployment)
# routes = [
#   { pattern = "api.yourdomain.com/*", custom_domain = true }
# ]

# Build configuration
[build]
command = ""

# Development configuration
[env.development.vars]
ENVIRONMENT = "development"